vector1.in:
  score: 0
  subtaskId: 1
vector2.in:
  score: 10
  subtaskId: 1
vector3.in:
  score: 10
  subtaskId: 1
vector4.in:
  score: 10
  subtaskId: 2
vector5.in:
  score: 10
  subtaskId: 2
vector6.in:
  score: 10
  subtaskId: 2
vector7.in:
  score: 10
  subtaskId: 2
vector8.in:
  score: 10
  subtaskId: 3
vector9.in:
  score: 10
  subtaskId: 3
vector10.in:
  score: 10
  subtaskId: 3
vector11.in:
  score: 10
  subtaskId: 3